author: "Brian Weatherson"
format: 
  beamer:
    aspectratio: 169
    fontsize: 14pt
    papersize: letter
    navigation: empty
    incremental: false
    innertheme: default
    outerthemeoptions: subsection = false
    colortheme: wolverine
    mainfont: SF Pro Text Light
    mainfontoptions: BoldFont = SF Pro Text Semibold, Scale = MatchLowercase
    keep-tex: false
    include-in-header:
        - 444-beamer-header.tex
        - kableextra-dependencies.tex




