---
title: "444 Lecture 4.6 - Utility"
author: "Brian Weatherson"
mainfont: SF Pro Rounded
output:
  beamer_presentation:
    md_extensions: +link_attributes+fenced_divs
    keep_tex: yes
    latex_engine: xelatex
    includes:
      in_header: 
        - 444-beamer-header.tex
        - extra-space.tex
        - kableextra-dependencies.tex
mathfont: STIX Two Math
mainfontoptions: BoldFont = SF Pro Rounded Semibold
---

```{r, include=FALSE}
source("kableformat.R")
```

## Plan

To introduce the notion of utility.

## Reading

Bonanno, chapter 5 - though note we aren't following the book precisely in this chapter.

## Ranking

- So far the theories we've looked just solve games using the **rankings** of various options. 
- It doesn't look at how much a player prefers one option over another, just on what is preferred to what.

## Ordinal Utility

- To use the technical language, so far our theories have just used  **ordinal utilities**. 
- The term **ordinal** here means that we only look at the **order** of the options. 

## Cardinal Utility

- The rules that we'll look at from now on use **cardinal utilities**.
- Whenever we're associating outcomes with numbers in a way that the magnitudes of the differences between the numbers matters, we're using cardinal utilities.

## Utility

- Intuitively, think of utilities as measuring how good an outcome is. 
- The theory we're building towards is thoroughly subjectivist, so think of 'how good' as meaning 'how good along all and only dimensions the agent making the decision cares about'. 

## Scale

- Utilities aren't really measured on any scale. 
- Indeed, like temperature measures, or year numberings, they don't even have a fixed zero point. 
- It is usually convenient to associate 0 utility with the status quo, and then have negative numbers for outcomes worse than status quo, and positive numbers for outcomes better than status quo. 
- But that's just a convention; you can set the 0 wherever you like. 
- And you can set the utility 1 point at anything better than 0.

## Scale (continued)

- But that's where the convention stops.
- Once you fix the 0 and 1 points, nothing else is fixed by pure convention.
- Temperatures are like this too.
- Though years are not - all the different calendars have years of the same length.

## Meaning of the Scale

We will come back to this much more in the future, but here is the key equation.

$$
U(B) = \frac{U(A) + U(C)}{2}
$$

Means that the agent is indifferent between getting $B$ for sure, and a coin flip that means they get $A$ if Heads and $C$ if Tails.

## Meaning of the Scale

It's a little unintuitive to think about this (though it helps if you've moved between Celsius and Farenheit countries).

- What matters is the ratio of differences.
- If $U(A) - U(B) = U(B) - U(C)$, that's really meaningful, even if none of the individual numbers are meaningful.

## For Next Time

- We will look at how utility relates to money.

