---
title: "444 Lecture 4.7 - Money and Utility"
author: "Brian Weatherson"
mainfont: SF Pro Rounded
output:
  beamer_presentation:
    md_extensions: +link_attributes+fenced_divs
    keep_tex: yes
    latex_engine: xelatex
    includes:
      in_header: 
        - 444-beamer-header.tex
        - extra-space.tex
        - kableextra-dependencies.tex
mathfont: STIX Two Math
mainfontoptions: BoldFont = SF Pro Rounded Semibold
---

```{r, include=FALSE}
source("kableformat.R")
```
## Plan

- In this lecture we'll talk about the relationship between money and utility.

## Associated Reading

Still chapter 5, though we're really not going page by page through this chapter.

## Don't Equate Dollars and Money

That's the message!

## Don't Equate Dollars and Money

> 1. Players might care how much money other players get.
> 2. Players might not assign the same utility to each dollar.

## Altruism

Consider an outcome where Player 1 gets $10 and Player 2 gets $20.

- Don't just say that's a utility of 10 for Player 1 and 20 for Player 2.
- Maybe Player 1 likes Player 2, and is happy they get some money - so this outcome has higher utility than one where Player 1 gets $10 and Player 2 gets $10.
- Maybe Player 1 has a hypotrophied sense of fairness and hates other people getting more - so this outcome has lower utility than one where Player 1 gets $10 and Player 2 gets $10.

## Resolving Social Problems

- Stepping back a bit, one of the big uses of game theory is in institutional design.
- We look at what game we are asking people to play, and use game theory to predict what they'll play, and if we don't like the answer, we think about changing the game to get a better one.
- Sometimes the most efficient way to get change is to change values - to get people to care about outcomes for others.

## Marginal Utility and Decision Making

- Getting $2x is not twice as valuable as getting $x.
- That's because it's like getting $x, then getting $x again.
- And after you get the first $x, you're richer, and getting $x is (in general) less valuable to richer people.

## Philosophical Point

It's relatively uncontroversial that the following two things are true. The philosophical claim that lies behind the theory I'm setting out in these slides is that they are closely connected.

1. You're better off getting a million dollars than getting a 50/50 shot at two million dollars.
2. Getting a million dollars changes your life more than it changes the life of a billionaire.

Both are grounded in the fact that the more money you have, the less utility each extra dollar has.

## Utility and Money

The graph of the relationship between utility and money should have the following two features.

1. More money means more utility.
2. The amount of extra utility you get for each extra dollar should be decreasing

Arguably utility rises with something like log of wealth.


## Insurance

Insurance is a funny business.

- Every insurance contract is a bet, with you and the insurance company on opposite sides of it.
- The bet can't, as a matter of almost mathematical necessity, have a positive expected dollar return for both of you.
- And given it involves some transaction costs, it could have a negative expected dollar return for both of you.
- So why does the industry even exist?

## Declining Marginal Utility

Well let's work through an example.

- Assume our person has assets of $100,000, including a car worth $30,000.
- They live in a risky area, so there is a 1 in 10 chance the car will fall in value to 0 over the next 12 months.
- They are offered an insurance contract with the following terms.
- They pay $3,200.
- If the risky thing happens and the car value falls to 0, the insurance company will reimburse them, so they will get the $30,000 back.

## Should They Take the Deal

Outcome if they take the deal

- A guaranteed $96,800. \pause

Outcome if they don't take the deal.

- A 90% chance of $100,000.
- A 10% chance of $70,000. \pause

The latter outcome has an expected dollar return of $97,000 - that's $0.9 \times 100,000 + 0.1 \times 70,000$.

## Should They Take the Deal

- But this doesn't settle the matter. We care about utility not dollars.
- Let's re-run the question using utility.

## Should They Take the Deal

Outcome if they take the deal

- A guaranteed $96,800, which has utility roughly 4.986  \pause

Outcome if they don't take the deal.

- A 90% chance of $100,000, which has utility 5.
- A 10% chance of $70,000, which has utility roughly 4.845 \pause

The latter outcome has an expected utility return of roughly $0.9 \times 5 + 0.1 \times 4.845 \approx 4.984$. Option 1 is better - not by much, but better.

## Company Point of View

- Assume (for now) that they have a constant marginal utility of money.
- So all that matters is that the policy has a positive dollar value.
- And the expected dollar return of the deal is +$200, so it's good for the company as well.

## Success!

- We found a case where both parties are rational in taking the bet, even though they are on opposite sides of it.
- And this doesn't require fraud, or misperception of the odds for either party.

## Possibility Constraints

- This is only possible because the two sides have different utility curves, at least locally.
- That's what makes the conflicting interests (in dollar terms) into a possible mutual interest.
- Someone with a less steeply sloping utility curve (i.e., with more resources) is in a better position to absorb certain risks.
- It is worth paying over the odds to them to absorb that risk.

## Curves (Almost) Always Slope Down

- But eventually, the insurance company has risks it shudders at as well.
- This only happens on enormous scale, but it happens.
- And it's why insurance companies won't (happily) offer insurance against correlated risks, like floods or invasion.

## A Big Caveat

When you run the numbers on cases like this, three things come out.

1. Sometimes, insurance is good for both parties. \pause
2. Unless the loss is a huge portion of the customer's wealth, the numbers end up being really close. \pause
3. Even in those cases, the numbers aren't that different.

So I end up thinking that people probably over-purchase insurance, even though this is a model on which insurance purchase can be rational.

## For Next Time

- We will take a very quick look at the nature of probability.