---
title: "444 Lecture 12"
subtitle: "Signals"
date: "February 16, 2023"
---

# Beer and Quiche

## The Beer-Quiche Game

- Sender's car breaks down on the way to work, so he walks into a bar to wait somewhere while the repair truck comes. (I think in the 1985 version he's looking for a phone.)
- He quickly realises this is a rougher bar than he expected, and the patrons are all staring at him.

## The Beer-Quiche Game

- Sender is smart, and he quickly realises that the patrons are both bullies and cowards. They're bullies, so they are looking for a fight, but cowards, so they won't fight a Tough Guy. And they think it's about 60% likely that he's a Tough Guy.
- Sender really wants to avoid a fight (whether or not he's a Tough Guy).
- He knows that if he just tries to leave, they will conclude that he too is a Wimp, so he better order something

## The Beer-Quiche Game

- His choices are beer or quiche.
- He knows that the patrons believe, correctly, that if he's a Tough Guy, he'd prefer beer, and if he's a Wimp, he'd prefer quiche.
- And while they can't read his character, they can hear his order.
- But he would also prefer not to get in a fight either way. Even Tough Guys have better things to do at 8 in the morning.

## {.plain}

\begin{center}
\begin{istgame}[scale=1.3]
   \xtdistance{20mm}{20mm}
   \istroot(0)[chance node]{$c$}
     \istb<grow=left>{0.6}[a]
     \istb<grow=right>{0.4}[a]
     \endist
   \xtdistance{10mm}{20mm}
   \istroot(1)(0-1)<180>{1}
     \istb<grow=north>{Beer}[l]
     \istb<grow=south>{Quiche}[l]
     \endist
   \istroot(2)(0-2)<0>{1}
     \istb<grow=north>{Beer}[r]
     \istb<grow=south>{Quiche}[r]
     \endist
   \istroot'[north](a1)(1-1)
     \istb{F}[bl]{1,-1}
     \istb{N}[br]{4,0}
     \endist
   \istroot(b1)(1-2)
     \istb{F}[al]{-1,-1}
     \istb{N}[ar]{2,0}
     \endist
   \istroot(a2)(2-2)
     \istb{F}[al]{-1,1}
     \istb{N}[ar]{4,0}
     \endist
   \istroot'[north](b2)(2-1)
     \istb{F}[bl]{-1,1}
     \istb{N}[br]{2,0}
     \endist
   \xtInfoset(a1)(b2){2}
   \xtInfoset(b1)(a2){2}
   \end{istgame}
\end{center}

## {.plain}

\begin{center}
\begin{istgame}[scale=0.9]
   \xtdistance{20mm}{20mm}
   \istroot(0)[chance node]{$c$}
     \istb<grow=left>{0.6}[a]
     \istb<grow=right>{0.4}[a]
     \endist
   \xtdistance{10mm}{20mm}
   \istroot(1)(0-1)<180>{1}
     \istb<grow=north>{Beer}[l]
     \istb<grow=south>{Quiche}[l]
     \endist
   \istroot(2)(0-2)<0>{1}
     \istb<grow=north>{Beer}[r]
     \istb<grow=south>{Quiche}[r]
     \endist
   \istroot'[north](a1)(1-1)
     \istb{F}[bl]{1,-1}
     \istb{N}[br]{4,0}
     \endist
   \istroot(b1)(1-2)
     \istb{F}[al]{-1,-1}
     \istb{N}[ar]{2,0}
     \endist
   \istroot(a2)(2-2)
     \istb{F}[al]{-1,1}
     \istb{N}[ar]{4,0}
     \endist
   \istroot'[north](b2)(2-1)
     \istb{F}[bl]{-1,1}
     \istb{N}[br]{2,0}
     \endist
   \xtInfoset(a1)(b2){2}
   \xtInfoset(b1)(a2){2}
   \end{istgame}
\end{center}

Sender gets (a) 3 points for avoiding fight; plus (b) +1 for liked order, -1 for disliked order.

## {.plain}

\begin{center}
\begin{istgame}[scale=0.9]
   \xtdistance{20mm}{20mm}
   \istroot(0)[chance node]{$c$}
     \istb<grow=left>{0.6}[a]
     \istb<grow=right>{0.4}[a]
     \endist
   \xtdistance{10mm}{20mm}
   \istroot(1)(0-1)<180>{1}
     \istb<grow=north>{Beer}[l]
     \istb<grow=south>{Quiche}[l]
     \endist
   \istroot(2)(0-2)<0>{1}
     \istb<grow=north>{Beer}[r]
     \istb<grow=south>{Quiche}[r]
     \endist
   \istroot'[north](a1)(1-1)
     \istb{F}[bl]{1,-1}
     \istb{N}[br]{4,0}
     \endist
   \istroot(b1)(1-2)
     \istb{F}[al]{-1,-1}
     \istb{N}[ar]{2,0}
     \endist
   \istroot(a2)(2-2)
     \istb{F}[al]{-1,1}
     \istb{N}[ar]{4,0}
     \endist
   \istroot'[north](b2)(2-1)
     \istb{F}[bl]{-1,1}
     \istb{N}[br]{2,0}
     \endist
   \xtInfoset(a1)(b2){2}
   \xtInfoset(b1)(a2){2}
   \end{istgame}
\end{center}

Hearer gets  1 point for fighting Wimp; -1 point for fighting Tough Guy.

## {.plain}

::: {.columns}

:::: {.column with="60%"}

\begin{center}
\begin{istgame}[scale=0.9]
   \xtdistance{20mm}{20mm}
   \istroot(0)[chance node]{$c$}
     \istb<grow=left>{0.6}[a]
     \istb<grow=right>{0.4}[a]
     \endist
   \xtdistance{10mm}{20mm}
   \istroot(1)(0-1)<180>{1}
     \istb<grow=north>{Beer}[l]
     \istb<grow=south>{Quiche}[l]
     \endist
   \istroot(2)(0-2)<0>{1}
     \istb<grow=north>{Beer}[r]
     \istb<grow=south>{Quiche}[r]
     \endist
   \istroot'[north](a1)(1-1)
     \istb{F}[bl]{1,-1}
     \istb{N}[br]{4,0}
     \endist
   \istroot(b1)(1-2)
     \istb{F}[al]{-1,-1}
     \istb{N}[ar]{2,0}
     \endist
   \istroot(a2)(2-2)
     \istb{F}[al]{-1,1}
     \istb{N}[ar]{4,0}
     \endist
   \istroot'[north](b2)(2-1)
     \istb{F}[bl]{-1,1}
     \istb{N}[br]{2,0}
     \endist
   \xtInfoset(a1)(b2){2}
   \xtInfoset(b1)(a2){2}
   \end{istgame}
\end{center}

::::

:::: {.column with="40%"}


Obvious Equilibrium

- Sender orders Beer if either Tough Guy or Wimp.
- Hearer doesn't fight if Beer, fights if Quiche.
::::

:::

## {.plain}

::: {.columns}

:::: {.column with="60%"}

\begin{center}
\begin{istgame}[scale=0.8]
   \xtdistance{20mm}{20mm}
   \istroot(0)[chance node]{$c$}
     \istb<grow=left>{0.6}[a]
     \istb<grow=right>{0.4}[a]
     \endist
   \xtdistance{10mm}{20mm}
   \istroot(1)(0-1)<180>{1}
     \istb<grow=north>{Beer}[l]
     \istb<grow=south>{Quiche}[l]
     \endist
   \istroot(2)(0-2)<0>{1}
     \istb<grow=north>{Beer}[r]
     \istb<grow=south>{Quiche}[r]
     \endist
   \istroot'[north](a1)(1-1)
     \istb{F}[bl]{1,-1}
     \istb{N}[br]{4,0}
     \endist
   \istroot(b1)(1-2)
     \istb{F}[al]{-1,-1}
     \istb{N}[ar]{2,0}
     \endist
   \istroot(a2)(2-2)
     \istb{F}[al]{-1,1}
     \istb{N}[ar]{4,0}
     \endist
   \istroot'[north](b2)(2-1)
     \istb{F}[bl]{-1,1}
     \istb{N}[br]{2,0}
     \endist
   \xtInfoset(a1)(b2){2}
   \xtInfoset(b1)(a2){2}
   \end{istgame}
\end{center}
::::

:::: {.column with="40%"}

Non-Obvious Equilibrium

- Sender orders Quiche if either Tough Guy or Wimp.
- Hearer doesn't fight if Quiche, fights if Beer.
::::

:::

## Mathematical Puzzle

- What constraints on equilibrium selection can rule out the non-obvious explanation?
- Really fun puzzle if you like puzzles, but not for us.
- The initial statement of the puzzle, and an idea for a solution, is in Cho and Kreps, _Signaling Games and Stable Equilibrium_, QJE 1987.
- If you like puzzles in this area, I highly recommend that paper.

## Our Lessons

- Nature may provide something like a 'character', or what Harsanyi called a 'type', to Sender.
- You don't have to think of this as some random event that occurs at a particular time, like the whimsical assignment of characters to the pre-infants in _Soul_.

## Our Lessons (cont.)

- All that matters is that there is some feature of Sender that Sender knows and Hearer doesn't.
- Well, and that Hearer's probability distribution over the possible types of Sender is common knowledge; this game gets nasty if the initial probability for Tough Guy is under 0.5.

## Our Lessons (cont)

- This is also a good example of a non-cooperative, but positive-sum, signaling game.
- And that's the kind of game that we're going to spend more time looking at in future lectures.

# Going to College

## The College Game

- Sender is deciding whether to go to college.
- There are two attributes of Sender that we're going to be interested in.
- They are either a High Value or Low Value employee.
- They will either Like or Dislike college.
- Let's assume that these attributes are perfectly correlated: all and only the High Value employees Like college.

## Features of College in this Game

> - College does not change anyone's value to employers - High Value employees are high value whether or not they go to college, and Low Value employees are low value either way.
> - College is fun for people who Like it (i.e., the High Values), but it's not so much fun to be actually worth the expense. But it's a relatively minor overpay for the people who Like it, and both unbearable and exorbitantly expensive for those who Dislike it.
> - I am *not* saying either of these are true, though I don't entirely disagree with the second.

## The Hiring Decision

- Hearer is an employer who pays high salaries, but gets good value for this high salary from High Value employees.
- Unfortunately, they have literally no way of telling who is High Value and who is Low Value.
- All they know is that only 40% of people are High Value.

## Payouts

- Everyone starts with 0 points, unless one of the conditions below is triggered.
- Sender gets 2 points if they get Recruited.
- They lose 1 point if they Like college and go to college.
- They lose 3 points if they Dislike college and go to college.
- Hearer gets 1 point if they Recruit a High Value Sender.
- They lose 1 point if they Recruit a Low Value Sender.


## {.plain}

\begin{center}
\begin{istgame}[scale=1.3]
   \xtdistance{20mm}{20mm}
   \istroot(0)[chance node]{$c$}
     \istb<grow=left>{0.4}[a]
     \istb<grow=right>{0.6}[a]
     \endist
   \xtdistance{10mm}{20mm}
   \istroot(1)(0-1)<180>{1}
     \istb<grow=north>{College}[l]
     \istb<grow=south>{Beach}[l]
     \endist
   \istroot(2)(0-2)<0>{1}
     \istb<grow=north>{College}[r]
     \istb<grow=south>{Beach}[r]
     \endist
   \istroot'[north](a1)(1-1)
     \istb{R}[bl]{2, 1}
     \istb{P}[br]{-1,0}
     \endist
   \istroot(b1)(1-2)
     \istb{R}[al]{3,1}
     \istb{P}[ar]{0,0}
     \endist
   \istroot(a2)(2-2)
     \istb{R}[al]{3,-1}
     \istb{P}[ar]{0,0}
     \endist
   \istroot'[north](b2)(2-1)
     \istb{R}[bl]{-1,-1}
     \istb{P}[br]{-3,0}
     \endist
   \xtInfoset(a1)(b2){2}
   \xtInfoset(b1)(a2){2}
   \end{istgame}
\end{center}

## Some Notes

- In the original Spence game, Sender gets to choose how much to spend on education from a range. They have infinitely many choices, not just the binary College/Beach choice. This doesn't really affect the analysis.
- What is crucial is that education is more costly for Low Value employees.

## Some Notes

- There are a lot of equilibria to this game, but the most natural is the separating equilibria, where Like/High go to college, and Dislike/Low go to the Beach.
- For reasons I don't know (but can guess about), the wikipedia page on signaling games is dire. This is odd because most of the game theory pages are really very good.

## Plausibility

Here are some ways in which the model (or at least the separating equilibrium of the model) does seem to look a bit like the real world.

- College grads get paid a lot more than non-grads.

## Plausibility

Here are some ways in which the model (or at least the separating equilibrium of the model) does seem to look a bit like the real world.

- It isn't immediately obvious how what we do here explains the higher pay.

## Plausibility

Here are some ways in which the model (or at least the separating equilibrium of the model) does seem to look a bit like the real world.

- Yet there is a ton of demand for places in college (at least pre-pandemic), and obviously a lot of demand for college grads.

## Plausibility

Here are some ways in which the model (or at least the separating equilibrium of the model) does seem to look a bit like the real world.

- College is more fun, i.e., less costly, for people with certain skills (perserverence, curiosity, writing/mathematical aptitude) that are independently valuable to employers.

## Implausibility

But there are several ways in which the model does not seem particularly plausible.

- At least after a few weeks/months/years in the job, employers have some ability to tell who is High Value, so if education was purely a signal, it should wear off after a little while.

## Implausibility

But there are several ways in which the model does not seem particularly plausible.

- The correlation between High Value and Liking college is a long way from perfect. At least in my day, the people who _really_ liked college were not at all what I'd think of as High Value employees for most businesses.

## Implausibility

But there are several ways in which the model does not seem particularly plausible.

- Even if the people who Dislike college really really hate calculus class, it's a little hard to see how they could hate it so much to turn down the college wage premium.

# Honest Signaling

## Signaling by Showing

- Change the game so that what options Sender has is a function of what type Sender is.
- In the extreme case, one type of Sender has two options, the other has one.
- In this case, Sender doing the thing that only their type can do is called **honest signaling** or **indexical signaling**.

## The Chase

- Sender sees that Hearer is trying to catch them, and it will be bad if Hearer succeeds.
- Maybe Hearer is a mugger, or maybe they are a cheetah and Sender is a springbok.
- Sender is either Strong or Weak.
- If they are Strong, they have the option of Jumping in the air before running away.
- This will slow them down, but will display their type to Hearer.

## Payoffs

- Sender loses 10 if they are chased and get caught.
- Hearer gains 5 if they catch Sender; but they lose 3 if they chase and fail (this might be an opportunity cost).
- Fast sender has a 20% chance of being caught if they don't Jump, and a 30% chance of being caught if they Jump.
- Slow sender can't jump, and has a 50% chance of being caught.

## {.plain}

\begin{center}
\begin{istgame}[scale=1.3]
   \xtdistance{20mm}{20mm}
   \istroot(0)[chance node]{$c$}
     \istb<grow=left>{0.4}[a]
     \istb<grow=right>{0.6}[a]
     \endist
   \xtdistance{10mm}{20mm}
   \istroot(1)(0-1)<180>{1}
     \istb<grow=north>{Jump}[l]
     \istb<grow=south>{Run}[l]
     \endist
   \istroot(2)(0-2)<0>{1}
     \istb<grow=south>{Run}[r]
     \endist
   \istroot'[north](a1)(1-1)
     \istb{C}[bl]{-3, -0.6}
     \istb{NC}[br]{0,0}
     \endist
   \istroot(b1)(1-2)
     \istb{C}[al]{-2,-1.4}
     \istb{NC}[ar]{0,0}
     \endist
   \istroot(a2)(2-1)
     \istb{C}[al]{-5,1}
     \istb{NC}[ar]{0,0}
     \endist
   \xtInfoset(b1)(a2){2}
   \end{istgame}
\end{center}

## Equilibria

- This one really looks like it should only have one equilibrium.
- If everyone does the same thing, i.e., Run, then Hearer's expected utility from Chasing is positive, so they will Chase everyone.
- But Fast Senders don't want this; they would prefer Jump plus No Chase to Run plus Chase.
- And if they Jump, Hearer will know it isn't worth Chasing.
- So the only sensible equilibrium is that Fast Senders Jump, and Hearer chases all and only Senders who Run (rather than Jumping).

## College

- Could there be an honest signaling explanation of why there is a college wage premium?
- Maybe; it seems relevant that some people aren't admitted to college and others could not complete it.
- But I don't know what such an explanation could look like.

## Can't/Won't

- In real life the boundary between a game where signaling is costly for one type and where it is impossible can be hard to draw.
- Especially for non-human animals, what exactly does it mean to say they could do something but choose not to because it is too expensive, rather than say that they can't.
- And for humans, we don't even consider some things to be viable options because they are prohibitively expensive.

## Can't/Won't

- Are these cases where something is not an option, or where it is rationally not chosen for expense.
- It isn't clear that much could, or should, turn on this.

## For Next Time

- Next week we will look more closely at Iterated Prisoners' Dilemma.
- The main reading is a long-ish 'handout' that I've posted to Canvas.