---
title: "444 Lecture 5.8 - Why Nash?"
author: "Brian Weatherson"
mainfont: SF Pro Rounded
output:
  beamer_presentation:
    md_extensions: +link_attributes+fenced_divs
    keep_tex: yes
    latex_engine: xelatex
    includes:
      in_header: 
        - 444-beamer-header.tex
        - extra-space.tex
        - kableextra-dependencies.tex
mathfont: STIX Two Math
mainfontoptions: BoldFont = SF Pro Rounded Semibold
---

```{r, include=FALSE}
source("kableformat.R")
```

## Plan

To look at the philosophical significance of Nash Equilibria.

## Reading

Bonanno, sections 2.6 (which we discussed earlier) and 6.4.

## Two Conjectures

1. It is rational to play any rationalizable strategy.
2. It is only rational to play Nash Equilibrium strategies

I'm going to end this week talking a bit about why people might prefer 2 over 1.

## One Intuitive Idea

- Don't just play Rock - the other person will figure it out.
- Rock every time is rationalizable.
- But you shouldn't do it.
- Therefore principle 1 must be false.

## Response 1

- Yeah, you shouldn't play Rock every single time, that's dumb.
- But on any given occasion, it's fine.
- And we know, from e.g., Prisoners' Dilemma, that we shouldn't infer what to do in a single shot game from what happens in the repeated game.

## Response 2

- The orthodox solution (i.e., principle 2) actually doesn't give you the result you might want here.
- It is possible that the randomising device will come up Rock every single time.
- So if you think it's always irrational to play Rock repeatedly, you have to think both of these are wrong.

## Response 3

- If principle 2 is right, all rational players will randomise every time.
- So the expected return of Rock is just the same as the expected return of randomisation.
- So it can't be wrong to play it.

## Mixing Response 2 and Response 3

- If principle 2 is right, and it's common knowledge that the players are rational, then the rational way to interpret the other player playing Rock every time is "Wow, their random device is having a freaky run."
- But if that's right, there isn't anything wrong with playing Rock every time.

## Other Direction

- As we'll see when we get to O'Connor's book, you mostly see people wanting more restrictions on moves than Nash.
- But Bonanno ends chapter 6 with an interesting reason for thinking even rationalisability (i.e., IDSDS) is too strong. \pause
- It's really incredibly unrealistic to know the utility function that the other player has.
- You might know the physical outcomes of the game, but knowing what utility each player gets is a huge assumption.
- So in practice, you should probably not rely too heavily on theories or policies that rely on this knowledge.

## For Next Time

- Next week we will do a bit of revision of probability theory.
- It's completely optional; if you want a week off, take a week off.
- After that, we'll look at how game theorists think about signals and messages.


