---
title: "444 Lecture 8.4 - Many Player Stag Hunt"
author: "Brian Weatherson"
mainfont: SF Pro Rounded
output:
  beamer_presentation:
    md_extensions: +link_attributes+fenced_divs
    keep_tex: yes
    latex_engine: xelatex
    includes:
      in_header: 
        - 444-beamer-header.tex
        - extra-space.tex
        - kableextra-dependencies.tex
mathfont: STIX Two Math
mainfontoptions: BoldFont = SF Pro Rounded Semibold
---

## Generalising

- The world doesn't have many 2 player 2 option games.
- If we're thinking of modelling real world situations, either as PD or Stag Hunt, we need something more general.

## Generalised Prisoners' Dilemma

- $n > 2$ players each choose a number $x$ in $[0, 1]$.
- The mean of the choices is $m$.
- Payoff to each player is $m - \frac{x}{r}$, for $r$ between $2$ and $n$.

## General Pattern

- If everyone picks the same number, better for everyone that that number is higher. \pause
- Holding fixed other players moves, it is always better to pick a lower number.

## Iteration

- It's really hard to do Axelrod-type stuff in these kinds of games.
- Just having the chance to interact again is not enough to push people to cooperate.
- There isn't enough freedom of movement; do you defect if 1 player out of 100 defects?

## Punishment

- Changing the payouts is a more effective move.
- So what we see in these kinds of situations is what is called 'altruistic punishment'.
- One person makes themselves temporarily worse off, and the perpetrator much worse off, to send a signal that defection will not be tolerated.
- Of course there is a free riding issue with who carries out the punishment, so ...

## Generalised Stag Hunt

- $n > 2$ players each choose a number $x$ in $[0, 1]$.
- The mean of the choices is $m$. \pause
- If a player chooses $x \leq m$, their payout is $x$. \pause
- If they choosee $x > m$, they receive $m - r(x - m)$, where $r > 1$ is some measure of how much one is penalised for leaving the equilibrium.

## General Pattern

- For any $x$, everyone choosing $x$ is a (strict) equilibrium.
- The higher $x$ is, the better this equilibrium is for everyone.
- Choosing 0 minimises regret, and maximises expected return given some natural distributions of probability to the other player's moves.

## Real World

- For something to be a real world stag hunt, those are the features you (approximately) need.
- The best thing to do is to do what everyone else does.
- If everyone does the same thing, better that everyone does the more cooperative thing.
- Given radical uncertainty about what others will do, best to do the uncooperative thing.

## For Next Time

- We'll talk through some examples of possible real life Stag Hunts.