---
title: "Assigment 2"
output:
  pdf_document:
    toc: false
    md_extensions: +startnum
    df_print: kable
    keep_tex: yes
    latex_engine: xelatex
    extra_dependencies: ["gensymb", "nicefrac", "caption", "istgame"]
    fig_caption: no
fontsize: 11pt
mainfont: SF Pro Text Light
geometry: margin=1in
author: Philosophy 444
date: Due 20 September, 2019
---

Most of the questions here ask you to solve a game using backwards induction. That is, we want you to say what strategies each player will play, if they use backwards induction reasoning. Remember that a _strategy_ in this sense has to say what a player would do at _every_ node, including nodes that are ruled out by their earlier moves.

## Questions 1-2

Here is the game tree for (one version of) the centipede game. The game works as follows. Before each turn, the experimenter puts \$2 into a pot in the middle of the table. This pot starts empty, and grows with every turn. At each turn, players choose whether to _Take_ or _Pass_. If they take, the money in the pot is split and the game ends. But it isn't split evenly; the player who takes the money gets \$2 more. So if there is \$68 in the pot, the player who takes gets \$35, and the other player gets \$33. The game ends when either one player takes the money, or if player 2 passes with \$200 in the pot. At this point, both players get \$100. Assume that both players only care about getting as much money for themselves as they can.

\begin{istgame}[scale=1.5]
   \setistgrowdirection{south east}
   \xtdistance{10mm}{20mm}
   \istroot(0)[initial node]{1}
     \istb{Take}[r]{(2,0)}[b]  \istb{Pass}[a]  \endist
   \istroot(1)(0-2){2}
     \istb{Take}[r]{(1,3)}[b]  \istb{Pass}[a]  \endist
   \istroot(2)(1-2){1}
     \istb{Take}[r]{(4,2)}[b]  \istb{Pass}[a]  \endist
   \xtInfoset(2-2)([xshift=5mm]2-2)
   %-------------
   \istroot(3)([xshift=5mm]2-2){2}
       \istb{Take}[r]{(97,99)}[b]  \istb{Pass}[a]  \endist
   \istroot(4)(3-2){1}
       \istb{Take}[r]{(100,98)}[b]  \istb{Pass}[a]  \endist
    \istroot(5)(4-2){2}
        \istb{Take}[r]{(99,101)}[b]  \istb{Pass}[a]{(100,100)}[r]  \endist
\end{istgame}

1. Use backwards induction to find the solution to the game.
2. Make two changes to the game. First, assume that there is a wealth tax in place - anything that a player collects over $50 has to be handed over to the government. Second, assume that players are _minimally_ altruistic. Given a choice between two options where they get the same amount, they prefer the other player to get more rather than less. (But they would still prefer to get more money than less, even if this costs the other player a lot.) Use backwards induction to solve this revised game.

Continues on next page.

\newpage

## Questions 3-5

There are two distinct proposals, A and B, being debated in Washington. The Congress likes proposal A, and the president likes proposal B. The proposals are not mutually exclusive; either or both or neither may become law. Thus there are four possible outcomes, and the rankings of the two sides are as follows (where as always a larger number means they prefer it).


```{r echo=FALSE, message=FALSE, warning=FALSE}
A <- c(4, 1)
B <- c(1, 4)
C <- c(3, 3)
D <- c(2, 2)
dataframe <- as.data.frame(rbind(A, B, C, D))
row.names(dataframe) <- c("A becomes law", "B becomes law", "Both A and B become law", "Neither A nor B becomes law")
names(dataframe) <- c("Congress", "President")
knitr::kable(dataframe, row.names=TRUE, caption="Schoolhouse Rock Game", align = "c")
```


The way legislation works (in this game) is as follows. First, Congress decides whether to pass a bill, and if so whether it will contain A only, B only, or both. Then the president decides whether to veto the bill or not. And that's it. (For simplicity, assume that there is no veto-override mechanism, and that there is no chance that the issue will get revisited.)

3. Use backwards induction to solve this game.
4. Change the rules, so the President gets a 'line-item veto'. That is, if Congress passes a law with both A and B in it, the President can veto just one of them, and let the other pass into law. Now, use backwards induction to solve _this_ game.
5. Explain intuitively why these games are different.

## Due Friday Sep 20, at 5pm
