---
title: "444 Class Four"
author: "Brian Weatherson"
date: "September 16, 2019"
output: 
  beamer_presentation:
    keep_tex: true
    latex_engine: xelatex
    includes:
      in_header: 305-beamer-header.tex
---

# Dynamic Games

## Slides!

- There won't normally be slides - but today is more lecture-y than normal.
- These are on Canvas; don't copy anything down.

## Class of Games We're Discussing

> - Two-player
> - Turn-taking
> - Finite
> - No hidden facts
> - No randomness
> - We'll start with zero-sum games, though drop this later.

## Five

- There are two players, who we'll call $A$ and $B$.
- First $A$ moves, then $B$, then finally $A$ moves again. 
- Each move involves announcing a number, 1 or 2. 
- $A$ wins if after the three moves, the numbers announced sum to 5. 
- $B$ wins otherwise. 

## Five

Question: How should you play this game?

## Game Tree for Five {.fragile}

\newcommand{\pictext}[3]{
\put(#1, #2){\makebox(0, 0)[b]{#3}}}
\begin{picture}(350, 150)
\pictext{175}{0}{$A$}
\put(175, 12){\circle{4}}\put(173, 13){\line(-2, 1){69}}
\put(177, 13){\line(2, 1){69}}
\pictext{135}{20}{1}
\pictext{215}{20}{2}
\pictext{105}{35}{$B$}
\put(105, 47){\circle*{4}}
\put(105, 47){\line(-1, 1){35}}
\put(105, 47){\line(1, 1){35}}
\pictext{80}{55}{1}
\pictext{130}{55}{2}
\pictext{245}{35}{$B$}
\put(245, 47){\circle*{4}}
\put(245, 47){\line(-1, 1){35}}
\put(245, 47){\line(1, 1){35}}
\pictext{220}{55}{1}
\pictext{270}{55}{2}
\pictext{70}{70}{$A$}
\put(70, 82){\circle*{4}}
\put(70, 82){\line(-1, 2){20}}
\pictext{50}{125}{$\mathpzc{L}$}
\put(70, 82){\line(1, 2){20}}
\pictext{90}{125}{$\mathpzc{L}$}
\pictext{55}{95}{1}
\pictext{85}{95}{2}
\pictext{140}{70}{$A$}
\put(140, 82){\circle*{4}}
\put(140, 82){\line(-1, 2){20}}
\pictext{120}{125}{$\mathpzc{L}$}
\put(140, 82){\line(1, 2){20}}
\pictext{160}{125}{$\mathpzc{W}$}
\pictext{115}{95}{1}
\pictext{155}{95}{2}
\pictext{210}{70}{$A$}
\put(210, 82){\circle*{4}}
\put(210, 82){\line(-1, 2){20}}
\pictext{190}{125}{$\mathpzc{L}$}
\put(210, 82){\line(1, 2){20}}
\pictext{230}{125}{$\mathpzc{W}$}
\pictext{195}{95}{1}
\pictext{225}{95}{2}
\pictext{280}{70}{$A$}
\put(280, 82){\circle*{4}}
\put(280, 82){\line(-1, 2){20}}
\pictext{260}{125}{$\mathpzc{W}$}
\put(280, 82){\line(1, 2){20}}
\pictext{300}{125}{$\mathpzc{L}$}
\pictext{265}{95}{1}
\pictext{295}{95}{2}
\end{picture}

$\mathpzc{W}$ means that $A$ wins, and $\mathpzc{L}$ means that $B$ wins.

## How to Solve These Games

> - Work backwards.
> - First, find points where a player has a choice between two terminal nodes.
> - Assume that they will make the choice that has higher value for them.$\pause$
> - Mark that choice, e.g., by doubling the line (as the textbook does) or bolding the line (as I'll do).
> - If there are ties, mark both of the lines. (This gets more complicated once we leave zero-sum games.)

## How to Solve These Games

> - Assign the value they choose to the choice node.
> - So just the game assigns values to terminal nodes, we'll now assign value to choice nodes.
> - In **Five**, we'll assign the value $\mathpzc{W}$ to the top right node.

## Five (after one step) {.fragile}

\newcommand{\pictext}[3]{
\put(#1, #2){\makebox(0, 0)[b]{#3}}}
\begin{picture}(350, 150)
\pictext{175}{0}{$A$}
\put(175, 12){\circle{4}}\put(173, 13){\line(-2, 1){69}}
\put(177, 13){\line(2, 1){69}}
\pictext{135}{20}{1}
\pictext{215}{20}{2}
\pictext{105}{35}{$B$}
\put(105, 47){\circle*{4}}
\put(105, 47){\line(-1, 1){35}}
\put(105, 47){\line(1, 1){35}}
\pictext{80}{55}{1}
\pictext{130}{55}{2}
\pictext{245}{35}{$B$}
\put(245, 47){\circle*{4}}
\put(245, 47){\line(-1, 1){35}}
\put(245, 47){\line(1, 1){35}}
\pictext{220}{55}{1}
\pictext{270}{55}{2}
\pictext{70}{70}{$A$}
\put(70, 82){\circle*{4}}
\put(70, 82){\line(-1, 2){20}}
\pictext{50}{125}{$\mathpzc{L}$}
\put(70, 82){\line(1, 2){20}}
\pictext{90}{125}{$\mathpzc{L}$}
\pictext{55}{95}{1}
\pictext{85}{95}{2}
\pictext{140}{70}{$A$}
\put(140, 82){\circle*{4}}
\put(140, 82){\line(-1, 2){20}}
\pictext{120}{125}{$\mathpzc{L}$}
\put(140, 82){\line(1, 2){20}}
\pictext{160}{125}{$\mathpzc{W}$}
\pictext{115}{95}{1}
\pictext{155}{95}{2}
\pictext{210}{70}{$A$}
\put(210, 82){\circle*{4}}
\put(210, 82){\line(-1, 2){20}}
\pictext{190}{125}{$\mathpzc{L}$}
\put(210, 82){\line(1, 2){20}}
\pictext{230}{125}{$\mathpzc{W}$}
\pictext{195}{95}{1}
\pictext{225}{95}{2}
\pictext{280}{70}{$\mathpzc{W}$}
\put(280, 82){\circle*{4}}
\thicklines
\put(280, 82){\line(-1, 2){20}}
\thinlines
\pictext{260}{125}{$\mathpzc{W}$}
\put(280, 82){\line(1, 2){20}}
\pictext{300}{125}{$\mathpzc{L}$}
\pictext{265}{95}{1}
\pictext{295}{95}{2}
\end{picture}

## Five (after first level) {.fragile}

\newcommand{\pictext}[3]{
\put(#1, #2){\makebox(0, 0)[b]{#3}}}
\begin{picture}(350, 150)
\pictext{175}{0}{$A$}
\put(175, 12){\circle{4}}\put(173, 13){\line(-2, 1){69}}
\put(177, 13){\line(2, 1){69}}
\pictext{135}{20}{1}
\pictext{215}{20}{2}
\pictext{105}{35}{$B$}
\put(105, 47){\circle*{4}}
\put(105, 47){\line(-1, 1){35}}
\put(105, 47){\line(1, 1){35}}
\pictext{80}{55}{1}
\pictext{130}{55}{2}
\pictext{245}{35}{$B$}
\put(245, 47){\circle*{4}}
\put(245, 47){\line(-1, 1){35}}
\put(245, 47){\line(1, 1){35}}
\pictext{220}{55}{1}
\pictext{270}{55}{2}
\pictext{70}{70}{$\mathpzc{L}$}
\put(70, 82){\circle*{4}}
\thicklines
\put(70, 82){\line(-1, 2){20}}
\pictext{50}{125}{$\mathpzc{L}$}
\put(70, 82){\line(1, 2){20}}
\thinlines
\pictext{90}{125}{$\mathpzc{L}$}
\pictext{55}{95}{1}
\pictext{85}{95}{2}
\pictext{140}{70}{$\mathpzc{W}$}
\put(140, 82){\circle*{4}}
\put(140, 82){\line(-1, 2){20}}
\pictext{120}{125}{$\mathpzc{L}$}
\thicklines
\put(140, 82){\line(1, 2){20}}
\thinlines
\pictext{160}{125}{$\mathpzc{W}$}
\pictext{115}{95}{1}
\pictext{155}{95}{2}
\pictext{210}{70}{$\mathpzc{W}$}
\put(210, 82){\circle*{4}}
\put(210, 82){\line(-1, 2){20}}
\pictext{190}{125}{$\mathpzc{L}$}
\thicklines
\put(210, 82){\line(1, 2){20}}
\thinlines
\pictext{230}{125}{$\mathpzc{W}$}
\pictext{195}{95}{1}
\pictext{225}{95}{2}
\pictext{280}{70}{$\mathpzc{W}$}
\put(280, 82){\circle*{4}}
\thicklines
\put(280, 82){\line(-1, 2){20}}
\thinlines
\pictext{260}{125}{$\mathpzc{W}$}
\put(280, 82){\line(1, 2){20}}
\pictext{300}{125}{$\mathpzc{L}$}
\pictext{265}{95}{1}
\pictext{295}{95}{2}
\end{picture}

## Next Steps Back

> - Now we do the same thing for $B$.
> - We act as if $B$ is choosing between terminal nodes.
> - It is as if $A$ doesn't have a choice - they will just make the choice that is best for them (i.e., worst for $B$).
> - So $B$ knows what the outcome of each choice will be.

## Five (After Two Rounds) {.fragile}

\newcommand{\pictext}[3]{
\put(#1, #2){\makebox(0, 0)[b]{#3}}}
\begin{picture}(350, 150)
\pictext{175}{0}{$A$}
\put(175, 12){\circle{4}}\put(173, 13){\line(-2, 1){69}}
\put(177, 13){\line(2, 1){69}}
\pictext{135}{20}{1}
\pictext{215}{20}{2}
\pictext{105}{35}{$\mathpzc{L}$}
\put(105, 47){\circle*{4}}
\thicklines
\put(105, 47){\line(-1, 1){35}}
\thinlines
\put(105, 47){\line(1, 1){35}}
\pictext{80}{55}{1}
\pictext{130}{55}{2}
\pictext{245}{35}{$\mathpzc{W}$}
\put(245, 47){\circle*{4}}
\thicklines
\put(245, 47){\line(-1, 1){35}}
\put(245, 47){\line(1, 1){35}}
\thinlines
\pictext{220}{55}{1}
\pictext{270}{55}{2}
\pictext{70}{70}{$\mathpzc{L}$}
\put(70, 82){\circle*{4}}
\thicklines
\put(70, 82){\line(-1, 2){20}}
\pictext{50}{125}{$\mathpzc{L}$}
\put(70, 82){\line(1, 2){20}}
\thinlines
\pictext{90}{125}{$\mathpzc{L}$}
\pictext{55}{95}{1}
\pictext{85}{95}{2}
\pictext{140}{70}{$\mathpzc{W}$}
\put(140, 82){\circle*{4}}
\put(140, 82){\line(-1, 2){20}}
\pictext{120}{125}{$\mathpzc{L}$}
\thicklines
\put(140, 82){\line(1, 2){20}}
\thinlines
\pictext{160}{125}{$\mathpzc{W}$}
\pictext{115}{95}{1}
\pictext{155}{95}{2}
\pictext{210}{70}{$\mathpzc{W}$}
\put(210, 82){\circle*{4}}
\put(210, 82){\line(-1, 2){20}}
\pictext{190}{125}{$\mathpzc{L}$}
\thicklines
\put(210, 82){\line(1, 2){20}}
\thinlines
\pictext{230}{125}{$\mathpzc{W}$}
\pictext{195}{95}{1}
\pictext{225}{95}{2}
\pictext{280}{70}{$\mathpzc{W}$}
\put(280, 82){\circle*{4}}
\thicklines
\put(280, 82){\line(-1, 2){20}}
\thinlines
\pictext{260}{125}{$\mathpzc{W}$}
\put(280, 82){\line(1, 2){20}}
\pictext{300}{125}{$\mathpzc{L}$}
\pictext{265}{95}{1}
\pictext{295}{95}{2}
\end{picture}


## Five (After Two Rounds)

- So we act as if getting to the left hand node means $B$ wins, and getting to the right hand node means $A$ wins.
- And now we just have to make the choice for the initial node, using this fact.

## Five (Full Graph) {.fragile}

\newcommand{\pictext}[3]{
\put(#1, #2){\makebox(0, 0)[b]{#3}}}
\begin{picture}(350, 150)
\pictext{175}{0}{$\mathpzc{W}$}
\put(175, 12){\circle{4}}\put(173, 13){\line(-2, 1){69}}
\thicklines
\put(177, 13){\line(2, 1){69}}
\thinlines
\pictext{135}{20}{1}
\pictext{215}{20}{2}
\pictext{105}{35}{$\mathpzc{L}$}
\put(105, 47){\circle*{4}}
\thicklines
\put(105, 47){\line(-1, 1){35}}
\thinlines
\put(105, 47){\line(1, 1){35}}
\pictext{80}{55}{1}
\pictext{130}{55}{2}
\pictext{245}{35}{$\mathpzc{W}$}
\put(245, 47){\circle*{4}}
\thicklines
\put(245, 47){\line(-1, 1){35}}
\put(245, 47){\line(1, 1){35}}
\thinlines
\pictext{220}{55}{1}
\pictext{270}{55}{2}
\pictext{70}{70}{$\mathpzc{L}$}
\put(70, 82){\circle*{4}}
\thicklines
\put(70, 82){\line(-1, 2){20}}
\pictext{50}{125}{$\mathpzc{L}$}
\put(70, 82){\line(1, 2){20}}
\thinlines
\pictext{90}{125}{$\mathpzc{L}$}
\pictext{55}{95}{1}
\pictext{85}{95}{2}
\pictext{140}{70}{$\mathpzc{W}$}
\put(140, 82){\circle*{4}}
\put(140, 82){\line(-1, 2){20}}
\pictext{120}{125}{$\mathpzc{L}$}
\thicklines
\put(140, 82){\line(1, 2){20}}
\thinlines
\pictext{160}{125}{$\mathpzc{W}$}
\pictext{115}{95}{1}
\pictext{155}{95}{2}
\pictext{210}{70}{$\mathpzc{W}$}
\put(210, 82){\circle*{4}}
\put(210, 82){\line(-1, 2){20}}
\pictext{190}{125}{$\mathpzc{L}$}
\thicklines
\put(210, 82){\line(1, 2){20}}
\thinlines
\pictext{230}{125}{$\mathpzc{W}$}
\pictext{195}{95}{1}
\pictext{225}{95}{2}
\pictext{280}{70}{$\mathpzc{W}$}
\put(280, 82){\circle*{4}}
\thicklines
\put(280, 82){\line(-1, 2){20}}
\thinlines
\pictext{260}{125}{$\mathpzc{W}$}
\put(280, 82){\line(1, 2){20}}
\pictext{300}{125}{$\mathpzc{L}$}
\pictext{265}{95}{1}
\pictext{295}{95}{2}
\end{picture}

## Five - Full Analysis

- The equilibrium state of the game is that $A$ wins.
- $A$ plays 2 first.
- Then $B$ can play anything they line.
- But whatever they do, $A$ will win, by playing the opposite number.

## Backwards Induction

- This process is called backwards induction.
- We start at the possible ends of the game.
- At each step, we assume that each player makes the best decision they can, on the assumption that later players will do the same thing.
- And eventually we can solve the game.

# Value of Games

## The Value of a Game

The value of a game is the outcome of the game if everyone does the backwards induction recommended move at every possible point.

## The Value of a Game

Every zero-sum game (that satisfies the earlier constraints) has a value.

\pause \bigskip

The value is the value of one of the terminal nodes.

\pause \bigskip

The proof is a fairly straightforward proof by induction, but I won't go through it here.

## The Value of a Game

So for any such game that ends with either win to one player or a draw, either

1. The first player can guarantee a win; or
2. The second player can guarantee a win; or 
3. Both players can guarantee at least a draw.

# Generalising

## A Complication

In a non-zero-sum game, a player might have a choice between two nodes that are alike for them, but are different for the other player.

## Indifferent Choices

\begin{picture}(350, 110)
\linethickness{1pt}
\pictext{175}{0}{I}
\put(175, 12){\circle*{4}}
\put(175, 12){\line(-2, 1){70}}
\put(175, 12){\line(2, 1){70}}
\pictext{135}{20}{$A$}
\pictext{215}{20}{$B$}

\pictext{105}{35}{II}
\put(105, 47){\circle*{4}}
\put(105, 47){\line(-1, 1){35}}
\pictext{70}{85}{(2, 2)}
\put(105, 47){\line(1, 1){35}}
\pictext{140}{85}{(0, 2)}
\pictext{80}{55}{$a$}
\pictext{130}{55}{$b$}

\pictext{245}{35}{II}
\put(245, 47){\circle*{4}}
\put(245, 47){\line(-1, 1){35}}
\pictext{210}{85}{(1, 2)}
\put(245, 47){\line(1, 1){35}}
\pictext{280}{85}{(3, 0)}
\pictext{220}{55}{$a$}
\pictext{270}{55}{$b$}

\end{picture}

## Indifferent Choices

- If player I chooses $B$, player II will choose $a$, ending the game at $(1,2)$.
- But what happens if player I chooses $A$?

## Duplicating the graph

> - You can't just draw two lines, because we need a value of the middle-left node for player I, and we don't know what that is.
> - The solution is to duplicate the graph.

## One Backwards Induction Solution

\begin{picture}(350, 110)
\linethickness{1pt}
\pictext{175}{0}{I}
\put(175, 12){\circle*{4}}
\thicklines
\put(175, 12){\line(-2, 1){70}}
\thinlines
\put(175, 12){\line(2, 1){70}}
\pictext{135}{20}{$A$}
\pictext{215}{20}{$B$}

\pictext{105}{35}{II}
\put(105, 47){\circle*{4}}
\thicklines
\put(105, 47){\line(-1, 1){35}}
\thinlines
\pictext{70}{85}{(2, 2)}
\put(105, 47){\line(1, 1){35}}
\pictext{140}{85}{(0, 2)}
\pictext{80}{55}{$a$}
\pictext{130}{55}{$b$}

\pictext{245}{35}{II}
\put(245, 47){\circle*{4}}
\thicklines
\put(245, 47){\line(-1, 1){35}}
\thinlines
\pictext{210}{85}{(1, 2)}
\put(245, 47){\line(1, 1){35}}
\pictext{280}{85}{(3, 0)}
\pictext{220}{55}{$a$}
\pictext{270}{55}{$b$}

\end{picture}

## Another Backwards Induction Solution

\begin{picture}(350, 110)
\linethickness{1pt}
\pictext{175}{0}{I}
\put(175, 12){\circle*{4}}
\put(175, 12){\line(-2, 1){70}}
\thicklines
\put(175, 12){\line(2, 1){70}}
\thinlines
\pictext{135}{20}{$A$}
\pictext{215}{20}{$B$}

\pictext{105}{35}{II}
\put(105, 47){\circle*{4}}
\put(105, 47){\line(-1, 1){35}}
\pictext{70}{85}{(2, 2)}
\thicklines
\put(105, 47){\line(1, 1){35}}
\thinlines
\pictext{140}{85}{(0, 2)}
\pictext{80}{55}{$a$}
\pictext{130}{55}{$b$}

\pictext{245}{35}{II}
\put(245, 47){\circle*{4}}
\thicklines
\put(245, 47){\line(-1, 1){35}}
\thinlines
\pictext{210}{85}{(1, 2)}
\put(245, 47){\line(1, 1){35}}
\pictext{280}{85}{(3, 0)}
\pictext{220}{55}{$a$}
\pictext{270}{55}{$b$}

\end{picture}

## What Should Player I Do?

Good question!

# Strategies and Threats

## Threat Game

\begin{picture}(350, 110)
\linethickness{1pt}
\pictext{175}{0}{I}
\put(175, 12){\circle*{4}}
\put(175, 12){\line(-2, 1){70}}
\put(175, 12){\line(2, 1){70}}
\pictext{135}{20}{$A$}
\pictext{215}{20}{$B$}

\pictext{105}{35}{II}
\put(105, 47){\circle*{4}}
\put(105, 47){\line(-1, 1){35}}
\pictext{70}{85}{(4, 1)}
\put(105, 47){\line(1, 1){35}}
\pictext{140}{85}{(1, 0)}
\pictext{80}{55}{$a$}
\pictext{130}{55}{$b$}

\pictext{245}{35}{II}
\put(245, 47){\circle*{4}}
\put(245, 47){\line(-1, 1){35}}
\pictext{210}{85}{(1, 1)}
\put(245, 47){\line(1, 1){35}}
\pictext{280}{85}{(2, 2)}
\pictext{220}{55}{$a$}
\pictext{270}{55}{$b$}

%\multiput(105,47)(5, 0){28}{\line(1, 0){3}}

\end{picture}


## Strategies

- A \textbf{strategy} for a game is a set of instructions for what to do at each node of a game.
- Even very small game trees there are a lot of possible strategies.
- If there are $k$ possible nodes a player could have a choice at, and $m$ possible moves at each of these nodes, then there are $m^k$ possible strategies.
- Note that a strategy has to say what to do at nodes that are ruled out by your own prior moves.

## Threat Game Strategies

- For player I, there are just two strategies: $A$ and $B$.
- For player II, there are two nodes, and two possible choices at each node. So there are $2^2 = 4$ possible strategies.
- We'll write $xy$ for the strategy of doing $x$ in response to $A$, and $y$ in response to $B$.
- And note I'm capitalising player I's moves, and using lower case for player II's moves, to make things clearer.

## Threat Game Strategies

Here are the four strategies for player II:

1. $aa$ - Do $a$ no matter what.
2. $ab$ - Do whatever player I does.
3. $ba$ - Do the opposite of what player I does.
4. $bb$ - Do $b$ no matter what.

## Threat Game Strategy Tables

The strategies for the players determine the outcome. Here is the table for the game, given the strategies.

\begin{center}
\begin{tabular}{l r | c c c c}
& & \multicolumn{4}{c}{Player II} \\
& & aa & ab & ba & bb \\ \hline 
\multirow{2}{*}{Player I} 
& A & 4, 1 & 4, 1 & 1, 0 & 1, 0 \\
& B & 1, 1 & 2, 2 & 1, 1 & 2, 2 
\end{tabular}
\end{center}

## Threat Game Strategy Tables

I've underlined the best responses.

\begin{center}
\begin{tabular}{l r | c c c c}
& & \multicolumn{4}{c}{Player II} \\
& & aa & ab & ba & bb \\ \hline 
\multirow{2}{*}{Player I} 
& A & \underline{4}, \underline{1} & \underline{4}, \underline{1} & \underline{1}, 0 & 1, 0 \\
& B & 1, 1 & 2, \underline{2} & \underline{1}, 1 & \underline{2}, \underline{2} 
\end{tabular}
\end{center}

There are three Nash equilibria.

1. $A, aa$ - with result 4, 1
2. $A, ab$ - with result 4, 1
3. $B, bb$ - with result 2, 2

## Threat Game with Backward Induction

\begin{picture}(350, 110)
\linethickness{1pt}
\pictext{175}{0}{I}
\put(175, 12){\circle*{4}}
\thicklines
\put(175, 12){\line(-2, 1){70}}
\thinlines
\put(175, 12){\line(2, 1){70}}
\pictext{135}{20}{$A$}
\pictext{215}{20}{$B$}

\pictext{105}{35}{II}
\put(105, 47){\circle*{4}}
\thicklines
\put(105, 47){\line(-1, 1){35}}
\pictext{70}{85}{(4, 1)}
\thinlines
\put(105, 47){\line(1, 1){35}}
\pictext{140}{85}{(1, 0)}
\pictext{80}{55}{$a$}
\pictext{130}{55}{$b$}

\pictext{245}{35}{II}
\put(245, 47){\circle*{4}}
\put(245, 47){\line(-1, 1){35}}
\pictext{210}{85}{(1, 1)}
\thicklines
\put(245, 47){\line(1, 1){35}}
\thinlines
\pictext{280}{85}{(2, 2)}
\pictext{220}{55}{$a$}
\pictext{270}{55}{$b$}

%\multiput(105,47)(5, 0){28}{\line(1, 0){3}}

\end{picture}

- I've bolded the best moves at each node, assuming backward induction.
- The path of best moves is the (in this case unique) backward induction solution.

## Threat Game

- There are three Nash equilibria of the game: strategy pairs that no one can improve on by unilaterally changing strategy.
- There is just one backward induction solution of the game: a strategy pair where everyone does the best they can \textbf{at every node} assuming others play rationally at every node.

# For Next Time

## Examples!

We will talk over some examples where backward induction reasoning might help understand what's going on.
